spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/housing-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1996
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.springframework.web: info
    com.auth0.application: TRACE

